# Generated by Django 4.1 on 2025-06-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='Avion',
        ),
    ]
